export type Module = {
  id: string
  name: string
  code: string
  mission: string
  skills: string[]
}

export const modules: Module[] = [
  {
    id: "automation",
    name: "Automation",
    code: "MOD-01",
    mission: "If a task repeats 3+ times, it becomes a system.",
    skills: [
      "Client onboarding sequence builder",
      "Delivery email pipeline",
      "Invoice + payment reminder flow",
      "Follow-up cadence scheduler",
      "Lead tracker auto-updater",
      "Proposal generator",
      "Contract template filler",
      "Review request automation",
      "Referral tracking flow",
      "Calendar + booking automation",
      "Form-to-CRM pipeline",
      "Automated status updates",
      "File delivery packager",
      "Recurring maintenance checklist runner",
      "Client intake form processor",
      "Quote calculator flow",
      "Deadline alert system",
      "Weekly metrics digest",
      "Content repurposing pipeline",
      "Social posting scheduler",
      "Backup automation",
      "Domain + hosting renewal alerts",
      "Failure-mode alerting (fail loudly)",
      "Automation blueprint template",
      "Automation-to-product converter",
    ],
  },
  {
    id: "scraping",
    name: "Scraping",
    code: "MOD-02",
    mission: "Turn public data into a daily pipeline of qualified leads.",
    skills: [
      "Broward permit scraper",
      "Miami-Dade permit scraper",
      "Permit trade filter",
      "Contractor license lookup",
      "Google Maps category scraper",
      "Business hours + rating extractor",
      "Website presence checker",
      "Contact info enrichment",
      "Email finder + verifier",
      "Phone number validator",
      "Lead scoring engine (1–10)",
      "Duplicate lead deduper",
      "Instagram business profile scraper",
      "Etsy seller scraper",
      "Facebook Marketplace scraper",
      "Local directory scraper",
      "Competitor site analyzer",
      "Review sentiment extractor",
      "Scrape scheduler + throttler",
      "Rate limit rotation strategy",
      "Scrape failure alerting",
      "CSV/database output formatter",
      "Lead nurture recycler (30-day)",
      "Scraped-data QA checklist",
      "Lead package builder (for resale)",
    ],
  },
  {
    id: "seo",
    name: "SEO",
    code: "MOD-03",
    mission: "Rank local businesses from a phone.",
    skills: [
      "Local keyword research flow",
      "Google Business Profile optimizer",
      "On-page SEO checklist",
      "Title + meta description generator",
      "Local citation builder",
      "Review generation flow",
      "Schema markup templates",
      "Competitor SEO gap analysis",
      "Content cluster planner",
      "Service page template (SEO-first)",
      "Location page generator",
      "Image alt + compression workflow",
      "Internal linking map",
      "Page speed audit flow",
      "Mobile-first QA for SEO",
      "FAQ schema generator",
      "Blog post SEO template",
      "Rank tracking sheet",
      "SEO monthly report template",
      "Backlink outreach scripts",
      "GBP post scheduler",
      "NAP consistency checker",
      "SEO client audit (sales weapon)",
      "SEO bundle pricing calculator",
      "SEO delivery SOP",
    ],
  },
  {
    id: "web-builds",
    name: "Web Builds",
    code: "MOD-04",
    mission: "Closed deal to live site in 48–72 hours, phone-only.",
    skills: [
      "5-section landing page template",
      "Restaurant site template",
      "Contractor site template",
      "Home services site template",
      "Demo page speed-build flow",
      "AI copywriting prompt chain",
      "Niche copy voice presets",
      "Logo + brand quick kit",
      "Color system generator",
      "Mobile QA checklist",
      "Contact form + lead capture setup",
      "Booking integration flow",
      "Review widget embed",
      "Gallery + before/after sections",
      "Service area map section",
      "Pricing table patterns",
      "Launch checklist",
      "Domain connection SOP",
      "Analytics setup flow",
      "Client preview + feedback loop",
      "Revision scope limiter",
      "Handoff documentation template",
      "Site maintenance checklist",
      "Template library manager",
      "Build time tracker",
    ],
  },
  {
    id: "outreach",
    name: "Outreach",
    code: "MOD-05",
    mission: "20–50 personalized touches a day, scaling to 100.",
    skills: [
      "Permit-based opener generator",
      "Demo-link opener generator",
      "3-touch follow-up cadence",
      "Objection handling scripts",
      "Two-option pricing pitch",
      "Same-day close script",
      "SMS outreach templates",
      "Email outreach templates",
      "DM outreach templates",
      "Voicemail script",
      "Personalization prompt chain",
      "Send-time optimizer",
      "Reply classifier (hot/warm/dead)",
      "Response time SLA tracker",
      "Outreach volume tracker",
      "A/B message testing log",
      "Nurture list manager",
      "Re-engagement campaign (30-day)",
      "Referral ask scripts",
      "Upsell scripts (maintenance $150/mo)",
      "Cross-sell scripts (SEO + automation)",
      "Outreach compliance checklist",
      "Daily outreach block SOP",
      "Pipeline review ritual (weekly)",
      "Close-rate calculator",
    ],
  },
  {
    id: "content",
    name: "Content",
    code: "MOD-06",
    mission: "Daily proof, weekly depth, every piece sells.",
    skills: [
      "Daily micro content formula",
      "Weekly long-form breakdown template",
      "Proof post formula",
      "Hook library (50 hooks)",
      "Build-in-public post template",
      "Before/after post template",
      "Client win post template",
      "Phone-only workflow demo script",
      "AI tool tutorial format",
      "Content calendar (30-day)",
      "CTA rotation system",
      "Content-to-Gumroad funnel map",
      "Repurposing matrix (1 idea → 5 posts)",
      "Caption prompt chain",
      "Thumbnail/cover generator flow",
      "Posting time optimizer",
      "Engagement reply scripts",
      "Comment-to-DM conversion flow",
      "Content metrics tracker",
      "Viral post autopsy template",
      "Niche content angles list",
      "Story/sequence format",
      "Long-form to newsletter flow",
      "Content batching SOP",
      "Content audit (monthly)",
    ],
  },
  {
    id: "delivery",
    name: "Delivery",
    code: "MOD-07",
    mission: "Five-star handoffs that generate reviews and referrals.",
    skills: [
      "Kickoff message template",
      "Asset collection checklist",
      "Midpoint preview flow",
      "Launch announcement template",
      "Walkthrough video script",
      "Automation pack handoff",
      "SEO setup handoff",
      "Client training one-pager",
      "Review ask flow (48hr)",
      "Referral offer flow",
      "30-day check-in template",
      "Maintenance plan pitch",
      "Support ticket log",
      "Issue → automation converter",
      "Delivery time tracker",
      "Quality gate checklist",
      "Client offboarding SOP",
      "Testimonial capture flow",
      "Case study builder",
      "Handoff document generator",
      "Payment collection SOP (50/50)",
      "Scope creep deflection scripts",
      "Emergency fix protocol",
      "Client satisfaction survey",
      "Five-star standards audit",
    ],
  },
  {
    id: "scaling",
    name: "Scaling",
    code: "MOD-08",
    mission: "From operator to owner: productize, bundle, compound.",
    skills: [
      "Weekly metrics review ritual",
      "Kill/scale decision framework",
      "Productization checklist",
      "Bundle strategy calculator",
      "Pricing ladder designer",
      "Gumroad launch SOP",
      "Product update cycle (monthly)",
      "Buyer email re-trigger flow",
      "Revenue per engine tracker",
      "Outreach scaling plan (50→100/day)",
      "Niche expansion framework",
      "Recurring revenue stacker",
      "Time audit (where hours go)",
      "Automation ROI calculator",
      "Skill documentation template",
      "OS module release process",
      "90-day plan generator",
      "Quarterly goals framework",
      "Capacity ceiling detector",
      "Subcontractor onboarding SOP (future)",
      "Systems debt tracker",
      "Founder energy management",
      "Cash flow forecast sheet",
      "Next-quarter product roadmap",
      "Exit-to-owner checklist",
    ],
  },
]
